// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz4SZXWEOvrWeyNaghTEcPDUdssjuQGzU',
    appId: '1:630900765193:web:ed184a145c9dccb824fed8',
    messagingSenderId: '630900765193',
    projectId: 'comissao-flutter-web',
    authDomain: 'comissao-flutter-web.firebaseapp.com',
    storageBucket: 'comissao-flutter-web.appspot.com',
    measurementId: 'G-L77N5KDH0B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmRZZKxZGLWtdAqLJI-d2s2RvXwTPDEXA',
    appId: '1:630900765193:android:86fc8c1cf06cc2b124fed8',
    messagingSenderId: '630900765193',
    projectId: 'comissao-flutter-web',
    storageBucket: 'comissao-flutter-web.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6tx2KHQmup2GmYPl8c9kqAQywvSI-alg',
    appId: '1:630900765193:ios:8bd0a93a5bebb7bc24fed8',
    messagingSenderId: '630900765193',
    projectId: 'comissao-flutter-web',
    storageBucket: 'comissao-flutter-web.appspot.com',
    iosBundleId: 'com.example.comissaoFlutterWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6tx2KHQmup2GmYPl8c9kqAQywvSI-alg',
    appId: '1:630900765193:ios:8bd0a93a5bebb7bc24fed8',
    messagingSenderId: '630900765193',
    projectId: 'comissao-flutter-web',
    storageBucket: 'comissao-flutter-web.appspot.com',
    iosBundleId: 'com.example.comissaoFlutterWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCz4SZXWEOvrWeyNaghTEcPDUdssjuQGzU',
    appId: '1:630900765193:web:88a4bdfa3b8ebf1d24fed8',
    messagingSenderId: '630900765193',
    projectId: 'comissao-flutter-web',
    authDomain: 'comissao-flutter-web.firebaseapp.com',
    storageBucket: 'comissao-flutter-web.appspot.com',
    measurementId: 'G-KN5KLCNMEL',
  );
}
